#!/bin/sh
apt install g++-10
git clone --recursive https://github.com/aristocratos/btop
cd btop/
make CXX='g++-10' LDFLAGS='-ldl'
sudo make install CXX='g++-10' LDFLAGS='-ldl' PREFIX='/notebooks/usr'
sudo make setuid CXX='g++-10' LDFLAGS='-ldl' PREFIX='/notebooks/usr'
