#!/bin/sh
# apt install g++-10
# git clone --recursive https://github.com/aristocratos/btop
cd btop/
#make CXX=g++-10 
sudo make install CXX=g++-10 PREFIX=/notebooks/usr
sudo make setuid CXX=g++-10 PREFIX=/notebooks/usr
# LDFLAGS='-ldl'
